apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        service: udagram-api-users
    name: udagram-api-users
spec:
    replicas: 1
    selector:
        matchLabels:
            service: udagram-api-users
    template:
        metadata:
            labels:
                service: udagram-api-users
        spec:
            containers:
                - image: 15huangtimothy/udagram-api-users
                  name: udagram-api-users
                  imagePullPolicy: Always
                  resources:
                      requests:
                          memory: "64Mi"
                          cpu: "250m"
                      limits:
                          memory: "1024Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 8080
            restartPolicy: Always
